#!/bin/bash

echo "Loading azd .env file from current environment"

# Use the `get-values` azd command to retrieve environment variables from the `.env` file
envValues=$(azd env get-values)

declare -A envDict

# Read the environment variables into an associative array
while IFS= read -r line; do
    if [[ $line =~ ^(.*?)=(.*)$ ]]; then
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]//\"/}" # Remove surrounding quotes
        envDict["$key"]="$value"
    fi
done <<< "$envValues"

ENV_CONTENT="# This file is automatically generated by the setup_local.sh script.
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=${envDict['AZURE_OPENAI_CHAT_DEPLOYMENT_NAME']}
AZURE_AI_FOUNDRY_CONNECTION_STRING=${envDict['AZURE_AI_FOUNDRY_CONNECTION_STRING']}

AZURE_AI_FOUNDRY_SUBSCRIPTION_ID=${envDict['AZURE_AI_FOUNDRY_SUBSCRIPTION_ID']}
AZURE_AI_FOUNDRY_RESOURCE_GROUP=${envDict['AZURE_AI_FOUNDRY_RESOURCE_GROUP']}
AZURE_AI_FOUNDRY_NAME=${envDict['AZURE_AI_FOUNDRY_NAME']}
AZURE_AI_FOUNDRY_PROJECT_NAME=${envDict['AZURE_AI_FOUNDRY_PROJECT_NAME']}
AZURE_TENANT_ID=${envDict['AZURE_TENANT_ID']}

SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true

LOGIC_APP_SUBSCRIPTION_ID=${envDict['LOGIC_APP_SUBSCRIPTION_ID']}
LOGIC_APP_RESOURCE_GROUP=${envDict['LOGIC_APP_RESOURCE_GROUP']}
LOGIC_APP_NAME=${envDict['LOGIC_APP_NAME']}
"

printf "%s" "$ENV_CONTENT" > .env