Write-Host "Loading azd .env file from current environment"

# Use the `get-values` azd command to retrieve environment variables from the `.env` file
$envValues = azd env get-values

$envDict = @{}

foreach ($line in $envValues -split "`n") {
    if ($line -match '^(.*?)=(.*)$') {
        $key = $Matches[1]
        $value = $Matches[2].Trim('"') # Remove surrounding quotes
        $envDict[$key] = $value
    }
}


# Build the .env content using keys from envDict
$envContent = @"
# This file is automatically generated by the setup_local.ps1 script.

AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=$($envDict['AZURE_OPENAI_CHAT_DEPLOYMENT_NAME'])
AZURE_AI_FOUNDRY_CONNECTION_STRING=$($envDict['AZURE_AI_FOUNDRY_CONNECTION_STRING'])

AZURE_AI_FOUNDRY_SUBSCRIPTION_ID=$($envDict['AZURE_AI_FOUNDRY_SUBSCRIPTION_ID'])
AZURE_AI_FOUNDRY_RESOURCE_GROUP=$($envDict['AZURE_AI_FOUNDRY_RESOURCE_GROUP'])
AZURE_AI_FOUNDRY_NAME=$($envDict['AZURE_AI_FOUNDRY_NAME'])
AZURE_AI_FOUNDRY_PROJECT_NAME=$($envDict['AZURE_AI_FOUNDRY_PROJECT_NAME'])
AZURE_TENANT_ID=$($envDict['AZURE_TENANT_ID'])

SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS=true
SEMANTICKERNEL_EXPERIMENTAL_GENAI_ENABLE_OTEL_DIAGNOSTICS_SENSITIVE=true

# Logic app standard with workflows for Office 365
LOGIC_APP_SUBSCRIPTION_ID=$($envDict['LOGIC_APP_SUBSCRIPTION_ID'])
LOGIC_APP_RESOURCE_GROUP=$($envDict['LOGIC_APP_RESOURCE_GROUP'])
LOGIC_APP_NAME=$($envDict['LOGIC_APP_NAME'])
"@


# Write to .env files
$envContent | Set-Content .env